### ISSUE TITLE
Crash in 1.18-rc1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [natanfudge/Not-Enough-Crashes#100]
While testing my modpack for release on the 30th, Minecraft crashed on launch with notenoughcrashes-4.1.1+1.18-pre5-fabric. If I disable Not Enough Crashes, the game launches as expected.

https://paste.ee/p/ZNPfx
[latest.log](https://github.com/natanfudge/Not-Enough-Crashes/files/7604380/latest.log)

**Comment by natanfudge** [comment]
Hey, please try updating to pre5 and see if the issue persists.

**Comment by ClaudiusMinimus** [comment]
It was working fine through pre7

**Comment by DragonEggBedrockBreaking** [comment]
I can confirm, it is broken on pre-release 7, 8, and release candidate 1. Works before that, though. And yes, this is with the latest build.

**Comment by natanfudge** [comment]
Fixed

**Comment by ClaudiusMinimus** [comment]
Seems to work fine.
Thanks!
