### ISSUE TITLE
Remove this interface

### ISSUE THREAD

**Issue by aaaapai** [natanfudge/Not-Enough-Crashes#104]
I can play games, but why should I look at this interface?
It is recommended to add a button to remove this interface
![Screenshot_20211207_222959_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/89151134/145049467-2228befd-3082-4121-8686-d4117a2fe1c3.jpg)

**Comment by natanfudge** [comment]
It's unclear what you mean. This interface is the main function of Not Enough Crashes.
