### ISSUE TITLE
When i'm playing, This world actually crashes and these texts are modified, bruh i'm really afraid.

### ISSUE THREAD

**Issue by Piwi2000** [natanfudge/Not-Enough-Crashes#107]
I was playing Minecraft ForgeOptifine 1.16.5, then, I created a new world with "Single Biome" and chooses badlands. I was started to play a new world, I was going to make a video with mutant beasts vs the clones, after 20 minutes of playing this world, my world just got crashed for real and suddenly, these texts are modified with any wrong texture texts. Can you fix it, natanfudge?

**Comment by natanfudge** [comment]
Please make your issue more clear.
