### ISSUE TITLE
Request: Just Enough Crashes

### ISSUE THREAD

**Issue by Piwi2000** [natanfudge/Not-Enough-Crashes#108]
Just Enough Crashes "or should I say JEC" is an Optimization Mod that allows Minecraft to improve better. Like inf+ FPS, No Crashes, and some more new optimization features:

NEC Bug Tracker "button, link to the current website"
Chunk Generator "slider"
No Fog "button, disabled or enabled"
And so much more!

It is similar to NEC (Not Enough Crashes)
If the mod is finished, The link will be published to CurseForge.

**Comment by natanfudge** [comment]
Not related to Not Enough Crashes
