### ISSUE TITLE
Mod incompatibility: LambdaControls 

### ISSUE THREAD

**Issue by Mhowser** [natanfudge/Not-Enough-Crashes#11]
The game crashes whenever I click on LC's config buttons

Here is the crash log: https://paste.dimdev.org/vinotaduno.mccrash

Here is LC's github: https://github.com/LambdAurora/LambdaControls

**Comment by natanfudge** [comment]
The link is dead

**Comment by Mhowser** [comment]
Hmm, it works for me, try the issues page https://github.com/LambdAurora/LambdaControls/issues

**Comment by natanfudge** [comment]
the crash log issue is dead, not the github

**Comment by natanfudge** [comment]
Fixed as of 1.2.2
