### ISSUE TITLE
Rework crash report uploading

### ISSUE THREAD

**Issue by ghost** [natanfudge/Not-Enough-Crashes#114]
Currently when crash reports are uploaded, they contain a lot of hardware info and software info. Additionally, they also individually identify the user through their Minecraft username. The uploaded logs are never deleted and have been indexed by search engines. This allows for anyone to search for a player's username and discover if there are any logs containing their information.

For some players concerned about their privacy, this poses a concern. I propose that uploaded logs should automatically delete after a certain amount of time, there's seemingly no reason for the logs to stay public permenantly. Another solution could be to implement a way for players to delete their own logs manually, though this would likely need more work.

**Comment by natanfudge** [comment]
NEC uses [Crashy](https://crashy.net/) as an alternate crash report site, and I plan to make it the default in the future.

**Comment by ghost** [comment]
Do you plan to purge the two years' worth of logs currently stored on GitHub?

**Comment by natanfudge** [comment]
No, it is sometimes useful to open up very old logs.
If there are specific problematic logs I will delete them manually.
