### ISSUE TITLE
something crashed with mixin(forge)

### ISSUE THREAD

**Issue by touhouzun** [natanfudge/Not-Enough-Crashes#118]
**Describe the bug**

**To Reproduce**
launch it.

**Crash Log:**
[latest.log](https://github.com/natanfudge/Not-Enough-Crashes/files/7919924/latest.log)

**Game Instance:**
notenoughcrashes-4.1.4+1.16.5-forge

**Comment by natanfudge** [comment]
Hey, what makes you think this is a NEC issue?

**Comment by touhouzun** [comment]
Well, I re-downloaded my launcher, .minecraft files, and 1.16.5-forge-36.2.23.
But it crashed on launching without any mod.
NsisoLauncher 4.8.7368.23222
[latest.log](https://github.com/natanfudge/Not-Enough-Crashes/files/7920212/latest.log)
I just feel...confused.

No, I'm stucked in re-downloading libraries. I couldn't believe it !
I have to close this for a while. Please forgive me:(
[latest.log](https://github.com/natanfudge/Not-Enough-Crashes/files/7920329/latest.log)

That's why I have to downgrade. Replaced jre8u321 with jre8u311. My fault:(
