### ISSUE TITLE
[FORGE 1.18.1] Crash menu opens, but the text is all in boxes.

### ISSUE THREAD

**Issue by RandomlyZay** [natanfudge/Not-Enough-Crashes#123]
**Describe the bug**

The crash screen that takes you back to the title screen and tells you which mods may have caused the crash is bugged. It just displays box characters instead of text (as seen below).

![image](https://user-images.githubusercontent.com/74725777/158085705-2ce6eeb2-5849-4701-bece-ad19a88cb6fd.png)

**To Reproduce**
1. Download my game instance
2. Start the instance (It will crash no matter what because there is a mod incompatibility somewhere)

**Crash Log:**
Link to the crash log, if relevant. You can upload a crash log by using [crashy](https://crashy.net/). 

Crashy keeps saying that there's something wrong with my crash log so I just used pastebin if that's okay.
[Crash Log](https://pastebin.com/4T2vDecz)

**Game Instance:**
Link to the curseforge/multimc game instance, or to a zip containing your game instance. For most issues, you must provide _something_ including the mods, saves, and configs you have used.

My Game Instance - [Creations-1.0.zip](https://github.com/natanfudge/Not-Enough-Crashes/files/8240927/Creations-1.0.zip)

**Comment by natanfudge** [comment]
Hey, thanks a lot for filling out the template, it will help me a lot in solving this!
I've opened a seperate Crashy issue for your crash log not being accepted: https://github.com/natanfudge/Crashy/issues/35

**Comment by RandomlyZay** [comment]
I found that one of the mods shown in red below stopped forge from telling me that 20 of the mods actually needed their libraries. I haven't seen if it fixed the box problem too, but it at least let Minecraft load enough to give me details instead of just telling me it crashed.

![image](https://user-images.githubusercontent.com/74725777/158283820-659a46c7-8b0d-493a-8596-b13ffa9db94e.png)

Basically, when I was trying to startup MC, notenoughcrashes was showing up first and telling me that Minecraft crashed, instead of getting to the forge menu that tells you that some mods are missing their libraries (menu below).

![image](https://user-images.githubusercontent.com/74725777/158284018-2ae1024d-44f8-4696-83e5-24df5ecff665.png)



EDIT: After adding the libraries, the game finally loaded normally which I really didn't expect to happen. Is there a way that you know of that could test your mod by intentionally crashing the game and going to the crash screen?

**Comment by natanfudge** [comment]
Sorry, I didn't notice your reply.
You can crash the game by holding f3+T.

**Comment by RandomlyZay** [comment]
I encountered the problem again, but this time, it's in 1.16.5. The exact same thing happens with only the boxes appearing as text. I'm looking right now to find the incompatible mod responsible. I'll get back as soon as I can.

EDIT: I found that the mod causing the issue was Chisel, but only because its library mod was not installed. That doesn't help much, but at least everything is normal. I feel like it's a problem with that mod instead of yours, because instead of doing the thing where it tells you that you need to install a library for a mod, it just crashes the game. And I just assume that MC hasn't loaded the font yet so the boxes replace the text everywhere.

**Comment by natanfudge** [comment]
Unfortunately I can't reproduce this issue using your instance.
