### ISSUE TITLE
Feature Request: Ticking Entities

### ISSUE THREAD

**Issue by HacoKavanah** [natanfudge/Not-Enough-Crashes#125]
Crashes caused by ticking entities usually just close minecraft, without even going to the launcher screen. Could this be made in such way that the mod would recognize these crashes and throw the user to the title screen like in other crashes?

**Comment by natanfudge** [comment]
Please provide an example instance of a ticking entity just closing the game. It should return to the title screen as normal.

**Comment by HacoKavanah** [comment]
[crash-2022-04-14_14.20.51-client.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/8492223/crash-2022-04-14_14.20.51-client.txt)
This is the crash report if that's what u asked for? There is really no way for me to replicate this, since the ticking entity crashes occur very randomly.

**Comment by HacoKavanah** [comment]
Same happened yesterday with "ticking world". I managed to fix the issue, but it surely would have been much easier to fix if not enough crashes just threw me to the title screen. If you have any idea of what could be happening, a fix could be really helpful! Thank you in advance!

**Comment by natanfudge** [comment]
From that crash log the crash screen should work fine. I will attempt to fix this if I have a way to reproduce it.
