### ISSUE TITLE
NEC keeping Jumploader in stack trace

### ISSUE THREAD

**Issue by QuasiCastle7479** [natanfudge/Not-Enough-Crashes#13]
The mods Jumploader, Fabic Rendering and Patchouli keep crashing the game during the loading time when entering a server. After removing Jumploader from the mods list with an open game, the server loading still crashes and throws up Jumploader as one of the causes. I was told this is because NEC is keeping Jumploader in the stack trace. The crash report is below.

https://gist.githubusercontent.com/Cloak-Bot/2881fe2a230373cac25fb5a82bd5862a/raw/3dd6b20d56ed4e6bb694dc840542e946e7998333/crash.txt

**Comment by natanfudge** [comment]
After removing a mod you must restart the game for it to take effect.
 May I know who told you “NEC is keeping jumploader in the stacktrace”?

**Comment by comp500** [comment]
What I meant is that NEC is blaming Jumploader for any crash that happens when it's installed, as it always appears in the stacktrace.

See https://github.com/comp500/Jumploader/issues/3

**Comment by natanfudge** [comment]
Ah I see that clears that up.
I don’t plan to change this for now but I may do it when I update the mod in the future (this is already done for fabric-loader).

**Comment by natanfudge** [comment]
Should be fixed as of [1.2.4](https://github.com/natanfudge/Not-Enough-Crashes/blob/ecd92a23b43c4cac91f301a46e344a75f80b0820/notenoughcrashes/src/main/java/fudge/notenoughcrashes/gui/ProblemScreen.java#L87).

**Comment by comp500** [comment]
Thanks!
