### ISSUE TITLE
[FABRIC 1.18.2] Crash Issue.

### ISSUE THREAD

**Issue by idontevenknowwhoiam** [natanfudge/Not-Enough-Crashes#130]
Hello, I would like to get help from you about my crash issue. I don't know if we're able to open issue for this but i hope you can help me. I started using your mods to detect the mods that causes crash and i was able to delete 1 mod that causes for me & my friend to get crash while we're on multiplayer but, after deleting that mod we was still getting crash issue and there wasn't enough clue for me to find what causes the crash. This crash issue only happens when we're on multiplayer and doesn't happens to both of us it only affects the other person who isn't started the server via LAN. Whenever i share the server with my friend that in same internet as me, we are able to play for few minutes then for some reason he's getting crash issue but nothing happens to me. Same goes for me too whenever he's the one who creates the server he getting crash too. I wasn't able to determine what's the problem because your mod wasnt giving me enough evidence. Would you please check the crashy link that i shared?

Also, sorry if this text is kinda long. 

[Crashy](https://crashy.net/eikjwuFGwoKxrJGJDFGn)

**Comment by natanfudge** [comment]
This is not a support forum. [Here](https://natanfudge.github.io/fudgedocs/binary-search-faulty-mod.html) is a useful text on resolving crashes. The Fabric discord may also be willing to help.
