### ISSUE TITLE
Mark v4.1.6 for Fabric as 1.19.1 and 1.19.2 compatible

### ISSUE THREAD

**Issue by ryanccn** [natanfudge/Not-Enough-Crashes#147]
[v4.1.6](https://modrinth.com/mod/notenoughcrashes/version/4.1.6%2B1.19-fabric) works fine on these versions, can you please mark it as such to make modpack management and mod downloaders have an easier time 🥺

**Comment by ryanccn** [comment]
https://github.com/natanfudge/Not-Enough-Crashes/issues/144 but for Modrinth

**Comment by natanfudge** [comment]
Lets see if modrinth will be so graceful as to allow me to upload 4.1.8.

**Comment by natanfudge** [comment]
Nope, I had to do it manually this time.
