### ISSUE TITLE
Not Enough Crashes crashes

### ISSUE THREAD

**Issue by alxpettit** [natanfudge/Not-Enough-Crashes#15]
Not Enough Crashes crashes when I try to upload the crash log to get the original crash fixed. [crash](https://paste.ee/p/J3fpS)

**Comment by natanfudge** [comment]
Hmm hopefully I won't have problems reproducing this

**Comment by alxpettit** [comment]
It does seem difficult to reproduce. A lot of interactions are possible. I'd be willing to share my modpack, world directory, config directory, and anything else that helps. Just let me know what you need! :)

**Comment by natanfudge** [comment]
It looks like github no longer likes the gist access token I used to give it, so I gave it a new one. 
I'll look into setting up my own site that won't break randomly and will have cool stuff like highlighting and remapping stack traces.

**Comment by natanfudge** [comment]
Fixed as of 2.1.1

**Comment by natanfudge** [comment]
https://github.com/elliotnash/fabricMods/blob/60056c5330ea7e27ea5a2363563ec1341aa6f085/mods/notenoughcrashes-1.2.4+1.15.1.jar
heh, this is what caused it
