### ISSUE TITLE
Discord link on here & modrinth expired.

### ISSUE THREAD

**Issue by akaEcho** [natanfudge/Not-Enough-Crashes#159]
Not a bug, just was gonna ask on discord in the config/notenoughcrashes.json file 

    "pastebin": {
      "uploadKey": "",
      "privacy": "UNLISTED",
      "expiry": "1 WEEK"

Is this the correct way to change it to unlisted & 1 week expiration on crash logs?

**Comment by natanfudge** [comment]
Discord link works fine for me.

**Comment by akaEcho** [comment]
Apologies, wasn't working in browser for me, works in discord client though.
