### ISSUE TITLE
[Quilt] Incompatible with Newest Sodium

### ISSUE THREAD

**Issue by SAJewers** [natanfudge/Not-Enough-Crashes#175]
**Describe the bug**
Attempt to run this with the newest version of Sodium (0.5.0) causes a Quilt "Failed to Load" crash.

Tested with Quilt Loader 0.19.2, QSL/QFAPI 7.1.0+0.86.1-1.20.1, Sodium 0.5.0, and Not Enough Crashes 4.4.6+1.20.1 only

**Crash Log:**
[crash-2023-08-05_21.04.01.1518-quilt_loader.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/12268460/crash-2023-08-05_21.04.01.1518-quilt_loader.txt)

**Comment by natanfudge** [comment]
See https://github.com/CaffeineMC/sodium-fabric/pull/1945
