### ISSUE TITLE
Not Enough Crashes, crashes newest fabric loader

### ISSUE THREAD

**Issue by Abalieno** [natanfudge/Not-Enough-Crashes#178]
**Describe the bug**
Crash on start notenoughcrashes-4.2.1+1.19.2-fabric
with Fabric Loader 0.15.0

This is due to something here:
https://github.com/FabricMC/fabric-loader/pull/812

"Seems like a mod depended on Loader internals that got changed in 0.15 (we migrated from the Tiny-Mappings-Parser library to Mapping-IO). Maybe contact the mod author if they could release an update? If they just need the mapping reader, they should bundle the library themselves instead of relying on Loader to to so"

**Crash Log:**
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/mapping/reader/v2/TinyVisitor

**Comment by natanfudge** [comment]
Hey, could you tell me if you experience the same issue in the latest versions of mc + nec?

**Comment by Abalieno** [comment]
Nope, 1.20.2 seems to be fine.

**Comment by natanfudge** [comment]
Thanks for reporting, I'm removed the reference to TMP in 1.19.2-5.0.0 so it should work now.
