### ISSUE TITLE
Launch crash screen not loaded correctly

### ISSUE THREAD

**Issue by NoobChester** [natanfudge/Not-Enough-Crashes#18]
![image](https://user-images.githubusercontent.com/60832458/90502899-2b32c600-e181-11ea-8b83-a48ae3b62ce5.png)

Crash log with this mod installed: https://paste.ee/p/yi1aT
Crash log without this mod installed: https://paste.ee/p/5edGn

Log with this mod installed: https://paste.ee/p/2h1KH
Log without this mod installed: https://paste.ee/p/nWzdE

Modlist:
1. https://github.com/PhiPro95/mc-fixes/releases/tag/lighting-fixes-v1.0.0
2. https://github.com/gudenau/minecraft-gudfps/releases/tag/v0.0.2
3. https://github.com/jellysquid3/phosphor-fabric/releases/tag/mc1.16.1-v0.6.0

Curseforge links for phosphor and gudFPS:
https://www.curseforge.com/minecraft/mc-mods/gudfps/files/3030046
https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2987621

I know this is quite complicated...hope these information helps :)

btw the crash only occurs when those three mods are all loaded, combinations like "1. 3." , "1. 2." , "2. 3." are fine.

**Comment by NoobChester** [comment]
https://github.com/jellysquid3/phosphor-fabric/issues/13#issuecomment-675417676
Someone told me the crash is due to phosphor and lighting-fixes being incompatible, gudFPS just makes it crash on launch.

**Comment by natanfudge** [comment]
I thing gudFPS fucks up the resource loading, which means there's not much I can do about it. I would start worrying if this happened with another mod.
