### ISSUE TITLE
Add option for F3+C instant crash

### ISSUE THREAD

**Issue by SemmieboyYT** [natanfudge/Not-Enough-Crashes#20]
I love this mod. But it has one simple problem. The instant crash. I use F3+C a lot to save my location, but now I can't. I tried adding the delay back but no luck. Please add an option for it.

**Comment by CalXee** [comment]
Yes, making it togglable would be nice.

**Comment by natanfudge** [comment]
I don't see the use for an instant crash, so I removed it.
