### ISSUE TITLE
Newest 1.16.2 version is in 1.16.1

### ISSUE THREAD

**Issue by PotatoPresident** [natanfudge/Not-Enough-Crashes#21]
2.1.4+1.16.2 is listed as 2.1.4+1.16.1 in the modmenu, latest.log, and in fabric.mod.json if I open it with 7zip
![7WtSPfkwed](https://user-images.githubusercontent.com/51728317/91745802-6913ef00-eb70-11ea-8940-1189924267ab.gif)

**Comment by teh404guy** [comment]
mods should work with newer version of minecraft if it doesnt break it / doesnt have version lock so this isnt an issue
