### ISSUE TITLE
1.16.3 support for NotEnoughCrashes?

### ISSUE THREAD

**Issue by James103** [natanfudge/Not-Enough-Crashes#23]
The latest version of NotEnoughCrashes (2.1.4) says that it is for 1.16.2. I'm on 1.16.3. Can the mod be updated to work on 1.16.3? If so, thank you.

**Comment by natanfudge** [comment]
Did you try it on 1.16.3?

**Comment by James103** [comment]
It does seem to work - this can be closed unless I find some actual problems with compatibility.
