### ISSUE TITLE
Apparently, iron golem spawners are tanking performance

### ISSUE THREAD

**Issue by Blobanium** [natanfudge/Not-Enough-Crashes#27]
If you put down a iron golem spawner, it instantaneously starts to lower FPS by almost half and spams the client log

Log: 
[latest.log](https://github.com/natanfudge/Not-Enough-Crashes/files/5491710/latest.log)

and a video show how much it impacts the FPS (pay attention to Rivatuner): https://streamable.com/vdr799

i decided to open an issue here because it mentioned "not enough crashes" in the logs

**Comment by SemmieboyYT** [comment]
This is not a Not Enough Crashes bug, that line is just because the mod is changing how Minecraft handles exceptions. Could you put the NBT data in a pastebin (if the NBT is small, just send it directly) and comment it? I think this is a vanilla bug or a fabric bug.

**Comment by Blobanium** [comment]
i think i might have did "/give <player> iron_golem_spawner"(replace <player> with username btw) and then placed it down then i get an FPS drop

**Comment by SemmieboyYT** [comment]
That is not an item, only spawner blocks exist. If you want to put an entity in it you will have to use nbt.

**Comment by Blobanium** [comment]
![unknown](https://user-images.githubusercontent.com/45613796/99698158-4c87a480-2a45-11eb-8dad-570df1563d64.png)
idk for u but apparently it showing iron_golem_spawner right for me

also i found it to be doing the same thing with bee spawners also

**Comment by natanfudge** [comment]
Wrong issue tracker
