### ISSUE TITLE
Running on dedicated servers?

### ISSUE THREAD

**Issue by Fourmisain** [natanfudge/Not-Enough-Crashes#28]
So I got a stupid question: Is this mod supposed to work on dedicated servers as well?
From the description I get that it's about 80% client side, but deobfuscated stack traces sounds like something that could also work on servers.

I'm asking because I found it conflicts with [jline4mcdsrv](https://github.com/chirs241097/jline4mcdsrv) ([Curseforge](https://www.curseforge.com/minecraft/mc-mods/jline-for-minecraft-dedicated-server)) and it fails a Mixin:
> [main/WARN] @Mixin target net.minecraft.class_1132 was not found notenoughcrashes.mixins.json:MixinIntegratedServer

jline4mcdsrv replaces the server command input loop of `MinecraftDedicatedServer` to add auto-completion and syntax highlighting but weirdly enough it can't even find the default `SysOut` log4j2 console appender ([here](https://github.com/chirs241097/jline4mcdsrv/blob/5426d3b1e3d2084d55a988cd462202722aa865ee/src/main/java/org/chrisoft/jline4mcdsrv/Console.java#L55)) with this mod installed, so maybe it causes some internal failure?

If NEC isn't supposed to run on dedicated servers, it might be a good idea to mark it as a client-side mod in ModMenu (see [ModMenu's wiki](https://github.com/TerraformersMC/ModMenu/wiki/API#client-)) and maybe add some description.

**Comment by natanfudge** [comment]
This mod is supposed to run on dedicated servers yes. I have updated `MixinIntegratedServer` to be client only as it should be. 
As for `jline4mcdsrv` I don't know how this mod can affect the default SysOut log4j2 console appender, so for know I'm going to ignore this incompatibility (unless someone really wants these 2 mods to be compatible).

**Comment by Fourmisain** [comment]
I tested it again with your new version - jline4mcdsrv *mostly* works now, except that (after jline4mcdsrv did it's logger changes) all log lines are for some bizarre reason doubled.

I'll open an issue on jline4mcdsrv's tracker to keep a tab on it for now.

**Comment by Fourmisain** [comment]
I did some debugging and I think I found the cause:
https://github.com/natanfudge/Not-Enough-Crashes/blob/d609012e61d7c37f1a807c6cddfe65c884b1e4b4/notenoughcrashes/src/main/java/fudge/notenoughcrashes/DeobfuscatingRewritePolicy.java#L19-L40

The `// Remove appender refs from config` part removes the `SysOut` appender and thus jline4mcdsrv can't find it.

I'm not yet sure if this is fixable in jline4mcdsrv - it could remove the `NotEnoughCrashesDeobfuscatingAppender` appender instead, though doing that would of course disable the deobfuscating - maybe there's a way to combine the features of both appenders...

**Comment by Fourmisain** [comment]
Just letting you know [that I may have fixed it in jline4mcdsrv](https://github.com/chirs241097/jline4mcdsrv/issues/5#issuecomment-766859189) - it's a hacky solution and untested, but it should work.
