### ISSUE TITLE
No icon in ModMenu

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [natanfudge/Not-Enough-Crashes#29]
This is less of a bug and more of a feature request, but I will include it anyway: There is no icon in Modmenu, even though all other mods have one. You can compare to the mods on either side in the attached image.

![image](https://user-images.githubusercontent.com/68545280/101952375-7a997800-3bf0-11eb-9053-2e9769d85420.png)

**Comment by natanfudge** [comment]
There was actually an icon, but it was black text on a transparent background, so you couldn't see shit. I've added a better icon. (Although it does kind of look shit in modmenu :/)
