### ISSUE TITLE
Github page is missing files in the releases page.

### ISSUE THREAD

**Issue by K0-RR** [natanfudge/Not-Enough-Crashes#38]

**Comment by natanfudge** [comment]
Not enough crashes is not distributed through github, but rather through CurseForge. Any releases here are a mistake.

**Comment by nfitzen** [comment]
@natanfudge why is this the case? It's so much easier to `curl -OL <release url>` on a server than to download it and FTP it up. To my knowledge, CurseForge doesn't support doing that.

**Comment by natanfudge** [comment]
Because users use Curseforge and not Github.
