### ISSUE TITLE
What's with these changelogs?

### ISSUE THREAD

**Issue by K0-RR** [natanfudge/Not-Enough-Crashes#39]
Changelog for just released 3.1.8 mentions not released 3.1.9. The same was for v3.1.7.
![Zrzut ekranu z 2021-03-04 21-16-28](https://user-images.githubusercontent.com/43277609/110032196-2823af80-7d38-11eb-8e00-5d38578d3cd4.png)
![Zrzut ekranu z 2021-03-04 21-16-55](https://user-images.githubusercontent.com/43277609/110032202-2954dc80-7d38-11eb-9d02-1a14c9f3d634.png)
![Zrzut ekranu z 2021-03-04 21-13-00](https://user-images.githubusercontent.com/43277609/110032208-29ed7300-7d38-11eb-9af0-2c8b71b38c78.png)

**Comment by natanfudge** [comment]
It is funny someone noticed. I don't remember exactly what happened, but let's just say version 3.1.8 and 3.1.9 are the same.
