### ISSUE TITLE
(Mod Conflict somewhere) Rendering errors and lockups on the crash screen

### ISSUE THREAD

**Issue by Blobanium** [natanfudge/Not-Enough-Crashes#40]
I dont really know whats happening here, but somehow on the crash screen is having text rendering issues and is locking up also. 

Screenshot of this happening (Right side of image)
![Capture](https://user-images.githubusercontent.com/45613796/111712735-768e7f00-880b-11eb-8e02-d1b7f6052ce4.PNG)

My mods(I need to narrow this down ill give you an update once ive managed to narrow this down)
![Capture2](https://user-images.githubusercontent.com/45613796/111713004-f87ea800-880b-11eb-99b4-1f7e7b6ef1e1.PNG)

if you need anything else while i search for whats breaking tell me thanks

**Comment by Blobanium** [comment]
Ok i managed to narrow it down mostly, but this happens to be such a complex bug that i already spent 3 hours trying to figure out what i need to reproduce this singular issue on another install, and probably it should be better if id send the entire install just so that i can confirm this bug actually exists, i know [this install](https://drive.google.com/drive/folders/1LnG94F3KtBXvEXaJtaVcR2cDpNQp0d1y?usp=sharing) has the issue present. (its located in diagnosis.zip btw i just added the MD5 Hash in the "hashes" doc right beside it)

also if you seem that you see that NotEnoughAnimations is the culprit the crash, that is a different bug and i already reported that on their end, i have that mod in there rn so i can reproduce this much more easily. 

just launch the install and try to loading into a world. thats how i got to reproduce that bug with that install.

**Comment by Blobanium** [comment]
ok so what i know so far is that its a resource pack that could be playing a role in this issue along with some other mods (Most likely optifabric)

**Comment by natanfudge** [comment]
Too complicated, if it happens again please reopen.
