### ISSUE TITLE
Provide a more user friendly configuration screen and file

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Not-Enough-Crashes#43]
Desired features:
1. comments
2. ingame GUI
3. Automatically add new config options when they are added in updates 
3. (optional) better format than json e.g. toml

**Comment by JonathanTippy** [comment]
yos

**Comment by Madis0** [comment]
[Cloth Config's AutoConfig](https://shedaniel.gitbook.io/cloth-config/auto-config/introduction-to-auto-config-1u) perhaps? Simple to use, lib itself is widely used so no need to bundle anything. 
Doesn't "automatically" add options, but they are just some variables defined in a class, so the syntax is easy. And it still uses JSON, not sure why you think TOML would be better.

**Comment by natanfudge** [comment]
Implemented as 4.4.0!
