### ISSUE TITLE
Unexpected error  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by seraphean** [natanfudge/Not-Enough-Crashes#46]
[crash log here](https://gist.githubusercontent.com/natanfudge/04da3e53c6ea894279b5816d924ddb12/raw/265b2cb404c83a8089913234ef49a840c72761e1/crash.txt),
can play for maybe 10-15 minutes before game crashes. NEC says no mods potentially causing it.

**Comment by natanfudge** [comment]
Not related to NEC.
