### ISSUE TITLE
Will this be updated to 1.17?

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [natanfudge/Not-Enough-Crashes#48]

**Comment by natanfudge** [comment]
If it does not yet work on 1.17, yes. Also I will be happily taking contributions since I don't have much time.

**Comment by natanfudge** [comment]
I will need some more time until tools update to 1.17.

**Comment by natanfudge** [comment]
An alpha release for 1.17 is available
https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/3349499
