### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by srnyx** [natanfudge/Not-Enough-Crashes#49]
Not Enough Crashes crashes (ironic lol) when using Iris with it.

**Comment by DragonEggBedrockBreaking** [comment]
I use both not enough crashes and iris together and they work fine. Your crash must be caused by something else. Please attach a crash report.

**Comment by srnyx** [comment]
> I use both not enough crashes and iris together and they work fine. Your crash must be caused by something else. Please attach a crash report.

Seems like it was just Sodium Extra. I had the wrong Sodium Extra file installed and I guess I forgot to test Not Enough Crashes with the new one.
Everything is working again though.

**Comment by natanfudge** [comment]
Thanks @DragonEggBedrockBreaking !
