### ISSUE TITLE
Provide an alternative for crash report hosting

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Not-Enough-Crashes#50]
Requirements:
- Up 100% of the time
- Ability for the author to delete uploaded crash report

Nice to have:
- Syntax Highlighting
- Identifier remapping
- Expiry date for crash reports
- Expiry date for link to crash report

**Comment by natanfudge** [comment]
My idea for this now is to create a dedicated site to nicely display crash reports, holding nice ui components representing the crash instead of a dump of text.

**Comment by Mhowser** [comment]
How about we use the [IPFS Protocol](https://ipfs.io)?

Edit: I just found this https://github.com/jes/hardbin

**Comment by natanfudge** [comment]
> Content on IPFS is not persistent and will eventually disappear from the IPFS network if it is not pinned anywhere (equivalent to "seeding" in bittorrent). To make the content persistent, you can either pin it on an IPFS node you control: $ ipfs pin add QmYqb4VHHKTVVzwa26FnBKtLsmUsq7RERmGzKywJUtEhYy

No, we can't run ipfs instances on user's computers.

**Comment by natanfudge** [comment]
Solved with [Crashy](https://crashy.net/)!
For further Crashy-related issues: https://github.com/natanfudge/Crashy/issues
