### ISSUE TITLE
Visual Studio Error trying to launch Minecraft

### ISSUE THREAD

**Issue by Dustin0530** [natanfudge/Not-Enough-Crashes#53]
I was following a guide for making a mod for Minecraft and got to the point of launching Minecraft but this is what I get. I cant find any solutions
![Screenshot (42)](https://user-images.githubusercontent.com/86275618/122854126-79988000-d2d0-11eb-801e-88c7f97ad890.png)

**Comment by natanfudge** [comment]
unrelated
