### ISSUE TITLE
Error identifying what mods are causing crash (1.17)

### ISSUE THREAD

**Issue by Blobanium** [natanfudge/Not-Enough-Crashes#55]
so im getting this everytime i crash
![Capture](https://user-images.githubusercontent.com/45613796/123335155-e9894f00-d4f8-11eb-9983-669ea5f6ebb5.PNG)

so yeah im opening an issue here
Heres the crash log:  [crash-2021-06-24_14.20.48-client.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/6712243/crash-2021-06-24_14.20.48-client.txt)

if you need anything else tell me thanks!

**Comment by natanfudge** [comment]
Please send your Minecraft instance.
What dis you do to trigger this crash?

**Comment by Blobanium** [comment]
[Heres my mc install](https://drive.google.com/file/d/1PVdPK0FHDmR6-Wpo99U3zYl_CT48Hk6O/view?usp=sharing) if thats what ur talking about

and how to reproduce
1. Start minecraft
2. Join any multiplayer server (idk if this works for singleplayer)
3. Disconnect from the server
4. the game crashes (you may have to resize the window to fully see the crash message)

**Comment by natanfudge** [comment]
Thanks, assuming that file contains your mods, config, and save files.

**Comment by natanfudge** [comment]
Fixed as of 3.4.2
