### ISSUE TITLE
Support Forge 1.17+

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Not-Enough-Crashes#62]
- Not Enough Crashes relies on a piece of software called [Mixin](https://github.com/SpongePowered/Mixin) that allows mods to make invasive changes to the game, such as preventing it from crashing altogether. 
- As of now, Forge does not support Mixin in 1.17+. NEC can only be updated once it is supported.

**Comment by PistonUser** [comment]
Why do you still use forge?

**Comment by natanfudge** [comment]
When it comes to NEC, I don't use Forge, I _target_ Forge. 
As for why would someone use Forge, one reason would be an abundance of content mods.

**Comment by PistonUser** [comment]
Ohhh oki :)

**Comment by natanfudge** [comment]
Forge 1.17.1 now supports mixins.
This is currently blocked by https://github.com/architectury/architectury-plugin/issues/23

**Comment by natanfudge** [comment]
Fixed as of 3.6.5
