### ISSUE TITLE
Bug Report: Still Connected to a Server after crashing

### ISSUE THREAD

**Issue by moehreag** [natanfudge/Not-Enough-Crashes#67]
I recognized that somehow I was still connected to Hypixel after having crashed (with the Message "You logged in from a different location"). You can also notice this when first joining Hypixel, then having a crash (with such a [Crash Report](https://bytebin.lucko.me/HMMWwY89Qo)) and at last, joining a different Server. The Hypixel chat messages are still being written. Here is a screenshot of this happening:
![2021-09-18_21 10 51](https://user-images.githubusercontent.com/85403855/133906040-66a6e6d2-de43-45f6-81cb-cde207212a1c.png) 

This might also be related to Osmium (https://github.com/Intro-Dev/Osmium/issues/15).

Other than that, your mod is very helpful and great!

**Comment by natanfudge** [comment]
Cool, I'll look into it

**Comment by natanfudge** [comment]
Fixed as of 3.4.5
