### ISSUE TITLE
Continuing the game after crashing will cause a crash report to be logged later when the game exits normally.

### ISSUE THREAD

**Issue by James103** [natanfudge/Not-Enough-Crashes#79]
When NotEnoughCrashes 3.6.5 is installed along with Minecraft 1.17.1, crashing the game and then continuing using "Back to title screen" will eventually result in a crash report being logged to your Minecraft log at the end of the game session.

To reproduce:
1. Install the aforementioned mods.
2. Start Minecraft.
3. Start a new world or join a world.
4. Hold F3+C for ten seconds.
5. NotEnoughCrashes catches the crash and lets you continue.
6. Do anything else...
7. Exit Minecraft.
8. Notice that the crash report is logged again at the end of the Minecraft Log.
9. Notice that the `Process exited with code -1.`

**Comment by natanfudge** [comment]
Thanks for the detailed report!
I'll try to tackle it this weekend.

**Comment by natanfudge** [comment]
Fixed in 3.7.0
