### ISSUE TITLE
crash when loading new world

### ISSUE THREAD

**Issue by ghost** [natanfudge/Not-Enough-Crashes#81]
crash when loading new world when updating notenoughcrashes from 3.4.4 to 3.7.0

minecraft 1.17.1
using java 16.0.1 64bit from AdoptOpenJDK
fabric loader 0.11.6
fabric api 41.0
optifabric 1.11.20 with optifine g9
other mods listed in crash report

[notenoughcrashes crash.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/7392028/notenoughcrashes.crash.txt)

**Comment by natanfudge** [comment]
Please try seeing if the same issue occurs without Not Enough Crashes. If not, please send your Minecraft instance ( mods folder, config, and data packs).

**Comment by ghost** [comment]
@natanfudge 
Okay through trial and error I narrowed it down to an incompatibility between notenoughcrashes and blur (when optifine is also present). On both the 3.4.4 and 3.7.0 version of not enough crahes. Tested with this mod list (no config or data packs)

- Fabric Loader 0.11.7
- Blur 2.3.0
- Fabric API 0.41.0
- Mod Menu 2.0.14
- Not Enough Crashes 3.7.0 (or 3.4.4)
- Optifabric 1.11.20
- OptiFine G9

When these mods are present and you try to load the game there will be a crash here is the report

[crash-2021-10-25_10.07.51-client.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/7411975/crash-2021-10-25_10.07.51-client.txt)

**Comment by natanfudge** [comment]
Thanks, that helps a lot.

**Comment by natanfudge** [comment]
This crash happens even when Not Enough Crashes is not installed. [proof](https://gist.github.com/natanfudge/6de654671fd7fa2efd5d14c18b12705e)
This is not a NEC issue.
