### ISSUE TITLE
Exiting world while F3+L profiling is active crashes recursively.

### ISSUE THREAD

**Issue by James103** [natanfudge/Not-Enough-Crashes#83]
Starting in Minecraft 1.17.1 (and possibly earlier), exiting the world while F3+L profiling is active crashes the game due to [MC-235964](https://bugs.mojang.com/browse/MC-235964).

However, when Fabric, Fabric API, and Not Enough Crashes 3.7.0 are installed, the crash becomes recursive, because the following exception is logged as a new profiler tick is attempted to be started while a profiler tick is already running.

To reproduce, follow the same reproduction steps as in [MC-235964](https://bugs.mojang.com/browse/MC-235964), which are copied below for your convenience.
1. Start Minecraft.
2. Create a new world or join a world.
3. Press F3+L.
4. Before the 10 seconds are up, exit the world by pressing Escape then clicking "Save and Quit to Title".
5. Notice the resulting crash.

When fixing this, I suggest aborting the profiler early if the game crashes during profiling, so that the recursive crash can be avoided.

The following two crash reports were logged one second apart from each other, likely caused by the above reproduction steps.
[crash-2021-10-25_16.54.57-client.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/7439849/crash-2021-10-25_16.54.57-client.txt)
[crash-2021-10-25_16.54.58-client.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/7439850/crash-2021-10-25_16.54.58-client.txt)

**Comment by natanfudge** [comment]
Wow, awesome work tracking down these issues. I'll take a look at this soon.

**Comment by natanfudge** [comment]
Fixed in 3.7.1.
