### ISSUE TITLE
Mod version 4.0.0 crashes on fabric loader 0.12.5

### ISSUE THREAD

**Issue by FinnishCrusader** [natanfudge/Not-Enough-Crashes#93]
Crash report: https://paste.ee/p/RlFHW

**Comment by natanfudge** [comment]
Very odd, I can't reproduce. Seems like a fabric loader problem.

**Comment by natanfudge** [comment]
Please try redownloading Not Enough Crashes 4.0.0-1.17.1 and using it again.

**Comment by FinnishCrusader** [comment]
Redownloading the mod worked, perhaps the jar corrupted. Anyways, solved
